# -*- coding: utf-8 -*-
"""GrammarCheck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMgDUR04b9qlpeKCX00FqQ4_pcVh0ncA
"""

import os

!pip install torch transformers

import torch
import transformers

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("prithivida/grammar_error_correcter_v1")
model = AutoModelForSeq2SeqLM.from_pretrained("prithivida/grammar_error_correcter_v1")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

sentences = [
    "She don't like to play basketball.",
    "I goes to the market every Sunday.",
    "He has ate dinner already.",
    "They was waiting for the bus.",
    "Me and him went to the park.",
    "She are my best friend.",
    "The cat chased it's tail.",
    "He runned very fast in the race.",
    "I seen the movie yesterday.",
    "They didn't knew the answer.",
    "Each of the students have a book.",
    "There is five apples on the table.",
    "The informations are not correct.",
    "She didn't told me about the party.",
    "I have went to the store.",
    "Neither of the answers are correct.",
    "He do not understand the question.",
    "Who's coat is this?",
    "Everybody have to bring their own lunch.",
    "We was excited about the trip."
]

corrected_sentences = []

for sentence in sentences:
    input_query = sentence.strip()
    input_ids = tokenizer.encode(input_query, return_tensors="pt").to(device)
    output_ids = model.generate(input_ids, max_length=128, num_beams=1, early_stopping=True)
    corrected_sentence = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    corrected_sentences.append(corrected_sentence)

for sentence in corrected_sentences:
    print(sentence)